nohup: ignoring input
INFO:     Started server process [16868]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [16868]
plication shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [16839]
nohup: ignoring input
INFO:     Started server process [16904]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
✅ OpenAI API Key encontrada: sk-proj-TV...
INFO:     127.0.0.1:54842 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:51494 - "POST /api/webhook/kiwify HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    response = await f(request)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/ubuntu/ia-nutricionista-backend/app/endpoints/webhook_kiwify.py", line 46, in kiwify_webhook
    payload = await request.json()
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/starlette/requests.py", line 250, in json
    self._json = json.loads(body)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 73 (char 72)
INFO:     127.0.0.1:56332 - "POST /api/webhook/kiwify HTTP/1.1" 200 OK
INFO:     127.0.0.1:41148 - "POST /api/webhook/kiwify HTTP/1.1" 200 OK
nohup: ignoring input
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [16904]
INFO:     Started server process [17010]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
/home/ubuntu/ia-nutricionista-backend/app/endpoints/webhook_kiwify.py:61: SAWarning: Column 'users.id' is marked as a member of the primary key for table 'users', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.
  conn.execute(insert(users).values(values))
✅ OpenAI API Key encontrada: sk-proj-TV...
INFO:     127.0.0.1:34322 - "POST /api/webhook/kiwify HTTP/1.1" 200 OK
nohup: ignoring input
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [17010]
INFO:     Started server process [17061]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
✅ OpenAI API Key encontrada: sk-proj-TV...
INFO:     127.0.0.1:41802 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:41806 - "POST /api/webhook/kiwify HTTP/1.1" 200 OK
INFO:     43.157.43.147:0 - "GET / HTTP/1.0" 200 OK
INFO:     43.157.43.147:0 - "GET / HTTP/1.0" 200 OK
INFO:     127.0.0.1:0 - "GET /health HTTP/1.0" 200 OK
INFO:     34.192.147.6:0 - "GET /health HTTP/1.0" 200 OK
INFO:     34.192.147.6:0 - "POST /api/webhook/kiwify HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [17061]
nohup: ignoring input
INFO:     Started server process [17227]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
✅ OpenAI API Key encontrada: sk-proj-TV...
INFO:     34.95.163.104:0 - "POST /api/webhook/kiwify?signature=9a9a9487156238c951b060da5fd3b4462461d17c HTTP/1.1" 200 OK
INFO:     34.95.238.190:0 - "POST /api/webhook/kiwify?signature=eb6ed485bf97d7a6d4424927f9a45c8dd4c8952e HTTP/1.1" 200 OK
INFO:     34.95.238.190:0 - "POST /api/webhook/kiwify?signature=3b752d407f716ef3e818708ed14ebaaa37cc19b3 HTTP/1.1" 200 OK
nohup: ignoring input
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [17227]
INFO:     Started server process [17669]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
nohup: ignoring input
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [17669]
INFO:     Started server process [17687]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
✅ OpenAI API Key encontrada: sk-proj-TV...
INFO:     127.0.0.1:60724 - "POST /api/webhook/kiwify?signature=08a99cff48c87ed082d33b1e172902f9f63e8caa HTTP/1.1" 200 OK
INFO:     34.192.147.6:0 - "POST /api/webhook/kiwify?signature=08a99cff48c87ed082d33b1e172902f9f63e8caa HTTP/1.1" 200 OK
INFO:     34.192.147.6:0 - "POST /api/webhook/kiwify?signature=WRONG HTTP/1.1" 401 Unauthorized
nohup: ignoring input
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [17687]
✅ OpenAI API Key encontrada: sk-proj-TV...
Traceback (most recent call last):
  File "/home/ubuntu/ia-nutricionista-backend/venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/ia-nutricionista-backend/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/ia-nutricionista-backend/app/main.py", line 82, in <module>
    from app.endpoints.webhook_kiwify import router as webhook_router
  File "/home/ubuntu/ia-nutricionista-backend/app/endpoints/webhook_kiwify.py", line 99
    subject = "���� Bem-vindo ao NutriFlow! Seus dados de acesso"
                                                                 ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
